server:
  port: 8080
spring:
  application:
    name: Learn Spring Batch
  datasource:
    url: jdbc:h2:file:C:/Users/harsh/code/db/learnspringbatch
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    jdbc:
      # to always initialize the datasource:
      initialize-schema: always
      # to only initialize an embedded datasource:
      # initialize-schema: embedded
      # to never initialize the datasource:
      # initialize-schema: never
    job:
      enabled: false
  jackson:
    serialization:
      indent_output: true